# Generated by Django 3.0 on 2019-12-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('urerid', models.IntegerField(primary_key=True, serialize=False)),
                ('IP', models.CharField(max_length=15)),
                ('Port', models.IntegerField()),
                ('remark', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('fromUserid', models.IntegerField(primary_key=True, serialize=False)),
                ('toUserid', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('plaintext', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('IdentityPub', models.CharField(max_length=64, null=True)),
                ('SignedPub', models.CharField(max_length=64, null=True)),
                ('OneTimePub', models.CharField(max_length=64, null=True)),
                ('ElephantPub', models.CharField(max_length=64, null=True)),
                ('IdentityPri', models.CharField(max_length=64, null=True)),
                ('SignedPri', models.CharField(max_length=64, null=True)),
                ('OneTimePri', models.CharField(max_length=64, null=True)),
                ('ElephantPri', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
