# Generated by Django 3.0 on 2019-12-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('IdentityPub', models.CharField(max_length=64, null=True)),
                ('SignedPub', models.CharField(max_length=64, null=True)),
                ('OneTimePub', models.CharField(max_length=64, null=True)),
                ('ElephantPub', models.CharField(max_length=64, null=True)),
                ('friends', models.CharField(max_length=2048, null=True)),
            ],
        ),
    ]
