# Generated by Django 3.0.4 on 2020-03-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUserid', models.IntegerField()),
                ('toUserid', models.IntegerField()),
                ('message', models.CharField(max_length=2048)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('IdentityPub', models.CharField(max_length=64, null=True)),
                ('SignedPub', models.CharField(max_length=64, null=True)),
                ('OneTimePub', models.CharField(max_length=64, null=True)),
                ('EphemeralPub', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
