# Generated by Django 3.0.1 on 2019-12-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191227_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ElephantPub',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.IntegerField(primary_key=True, serialize=False, unique=True), max_length=64),
        ),
    ]
